[package]
name = "scene"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.3"
log = "0.4.17"
strale = { path = "../../lib/strale" }
vulkano-win = "0.31.0"
winit = "0.27.5"
